server:
  port: 5001

spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true       # 开启以服务id去注册中心上获取转发地址
gateway:
  router:
    nacos:
      config:
        dataId: gateway-router # 网关nacos dataId配置
        group: DEFAULT_GROUP   # 网关nacos group配置