server:
  port: 10801
dubbo:
  scan:
    base-packages: com.dubbo.consumer.rpc
  registry:
    address: nacos://127.0.0.1
    port: 8848
    use-as-config-center: false
    use-as-metadata-center: false
  #    protocol: nacos
  application:
    name: ${spring.application.name}
    qos-enable: false
    version: 1.0.1
  protocol:
    port: -1
    name: dubbo
  cloud:
    subscribed-services: dubbo-spring-cloud-provider
  # 链路追踪
  consumer:
    check: false
    filter: tracing
  # 链路追踪
  provider:
    filter: tracing
spring:
  application:
    name: dubbo-spring-cloud-consumer
  #  profiles:
  #    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #      config:
  #        server-addr: 116.62.101.0:8848
  #        file-extension: yaml
  #        namespace: 66b394c6-e824-4489-a93a-535933bb57d9
  #        group: DEFAULT_GROUP
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
